/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rock.paper.scissors;

import javafx.scene.layout.AnchorPane;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;

//TODO fix colour scheme
//TODO add sound

public class App extends Application{

    static LinkedList<IShutDownListener> shutdownListeners;
    static LinkedList<IScreenChangeListener> scrnChangeListeners;
    static LinkedList<IMovePlayedListener> movePlayedListeners;
    static LinkedList<IGameResultListener> gameResultListeners;
    static final int VIDEO_SCREEN = 1;
    static final int VS_HAND_SCREEN = 2;
    static final int NO_HAND_SCREEN = 3;
    static final int RESULT_SCREEN = 4;
    static AnchorPane root;
    static ArrayList<AnchorPane> screens; //stores all the different screens
    static int currentScreenIndex;

    @Override
    public void start(Stage stage) throws IOException {
        root = (AnchorPane) FXMLLoader.load(getClass().getResource("anchor.fxml"));
        screens.add((AnchorPane) FXMLLoader.load(getClass().getResource("gui-start.fxml")));
        screens.add((AnchorPane) FXMLLoader.load(getClass().getResource("gui-play.fxml")));
        screens.add((AnchorPane) FXMLLoader.load(getClass().getResource("gui-vs.fxml")));
        screens.add((AnchorPane) FXMLLoader.load(getClass().getResource("gui-no-hand.fxml")));
        screens.add((AnchorPane) FXMLLoader.load(getClass().getResource("gui-result.fxml")));

        root.getChildren().add(screens.get(0)); //add start window
        Scene scene = new Scene(root, 640, 400);

        stage.setOnCloseRequest(windowEvent -> {
            alertShutDownListeners();
            stage.close();
        });

        stage.setTitle("Rock Paper Scissors!");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {

        shutdownListeners = new LinkedList<>();
        scrnChangeListeners = new LinkedList<>();
        movePlayedListeners = new LinkedList<>();
        gameResultListeners = new LinkedList<>();
        screens = new ArrayList<>();
        currentScreenIndex = 0;
        launch();
    }
    public static void addScrnChangeListener(IScreenChangeListener listener){
        scrnChangeListeners.add(listener);
    }
    static void alertScrnChangeListeners(){
        for (IScreenChangeListener listener: scrnChangeListeners) {
            listener.onScreenChange(currentScreenIndex);
        }
    }

    public static void addShutDownListener(IShutDownListener listener){
        shutdownListeners.add(listener);
    }
    static void alertShutDownListeners(){
        for (IShutDownListener listener: shutdownListeners) {
            listener.onShutDown();
        }
    }

    public static void addGameResultListener(IGameResultListener listener){
        gameResultListeners.add(listener);
    }
    static void alertGameResulListeners(int result){
        for (IGameResultListener listener: gameResultListeners) {
            listener.onGameResult(result);
        }
    }

    public static void setPlayerMove(int move) { alertMovePlayedListeners(move, true);}

    public static void makeComputerMove() {alertMovePlayedListeners(GameLogic.GetComputerMove(), false);}

    public static void addMovePlayedListener(IMovePlayedListener listener){
        movePlayedListeners.add(listener);
    }
    static void alertMovePlayedListeners(int movePlayed, boolean isPlayer){
        for (IMovePlayedListener listener: movePlayedListeners) {
            listener.onMovePlayed(movePlayed, isPlayer);
        }
    }

    public static void setGameResult(int result){
        alertGameResulListeners(result);
    }

    public static AnchorPane getScreen(int i){
        return screens.get(i);
    }

    public static void setScreen(int i){
        root.getChildren().remove(0);
        root.getChildren().add(getScreen(i));
        currentScreenIndex = i;
        alertScrnChangeListeners();
    }

}
